### ISSUE TITLE
Allow the VERSION constant to dictate releases

### ISSUE THREAD

**Issue by gschorkopf** [fastly/fastly-php#15]
We now have a "single source of truth" for our package's version: https://github.com/fastly/fastly-php/blob/master/src/Fastly.php#L12

Let's make sure that, upon releasing / bumping releases for this package, we use this constant. This might need to include a README update.

**Comment by alieander** [comment]
We don't have a lot of in house PHP deployments and are not sure the best or well practiced way todo this in the PHP world.

If anyone has the time or would like to help out, we would love anything from a simple suggestion to a full on PR!

❤️ 👍 ⭐
