### ISSUE TITLE
TlsBulkCertificatesResponse deserialization

### ISSUE THREAD

**Issue by malachy-mcconnell** [fastly/fastly-php#36]
**Version**

1.0.0-alpha2

**What happened**

The classes and properties in the autogenerated models don't seem to match the API JSON response, in particular for TlsBulkCertificatesResponse but I am suspicious of any Response class that lists `'data' => '\Fastly\Model\Data'` (or '\Fastly\Model\Data[]') because `\Fastly\Model\Data` is not a class in this library.

The result is that the deserializer can't figure out what classes it is to use for the object returned by the API

Here are my notes:

I am running into problems with object deserialization. Please can you give some insight into how the model classes and the deserializer function are autogenerated?

Specifically, I would like to poll the API for a list of certificates via the TLS Bulk Certificates API. However the data types (Model classes) aren’t defined properly or the deserializer is not able to discern the model class from the JSON stdClass ‘type’ property. It’s hard to explain.

As a starting point, for example, I would expect to see `'data' => '\Fastly\Model\TlsBulkCertificateData[]'` [here](https://github.com/fastly/fastly-php/blob/6faaf2c22f80c27649b42705449056266dfc762a/lib/Model/TlsBulkCertificatesResponse.php#L58)

```
TlsBulkCertificatesResponse.php
        'data' => '\Fastly\Model\Data[]'
```

The deserializer suffers further because it can’t understand how to convert the string [AnyOfRelationshipTlsConfigurationsObject' into a class name](https://github.com/fastly/fastly-php/blob/6faaf2c22f80c27649b42705449056266dfc762a/lib/Model/TlsBulkCertificateData.php#L57).

```
TlsBulkCertificateData.php
        'relationships' => 'AnyOfRelationshipTlsConfigurationsObject',
```

Anyway, we can see the auto-generation of the bulk TLS certificate response sub classes is not correct. I get the feeling the code isn’t developed fully or this alpha version doesn’t have full support for all the generated endpoints.

Can you give me any advice on whether I have completely misunderstood how to use the SDK or if it is a work-in-progress and if it is a work in progress is there anything I can do to help (notwithstanding it seems to be entirely autogenerated from some meta API description)?

Thank you.

**Comment by Integralist** [comment]
👋🏻

v1.0.0 has now been published https://packagist.org/packages/fastly/fastly 

Let us know if this is still an issue for you.

Thanks.
