### ISSUE TITLE
Stable v1.0 Release

### ISSUE THREAD

**Issue by szainmehdi** [fastly/fastly-php#41]
We use v0.4.1 of this library and are in the process of upgrading to PHP 8. It looks like v1 releases of this package support PHP 8 but are not marked as stable yet. Is a stable v1 release coming soon?

If not, can we get a v0.4.2 release with PHP 8 support?

Thank you!

**Comment by Integralist** [comment]
Hi @szainmehdi 

Thanks for opening this issue.

We currently have no plans to update the PHP version for the 0.x range of releases but we do have plans to stabilise the 1.x beta release soon. Unfortunately, I can't give an exact timeline, but it is being worked on.

We'll update this issue once we're ready to release.
