### ISSUE TITLE
`purgeSingleUrl` gives "malformed purge request" error

### ISSUE THREAD

**Issue by chaseconey** [fastly/fastly-php#46]
**Version**

1.2.0

**What happened**

When making purge requests via the SDK using the `PurgeApi` client's `purgeSingleUrl` function, it is encoding the value and resulting in the following error:

```
[400] Client error: `POST https://api.fastly.com/purge/example.com%2Fslug%2F` resulted in a `400 Bad Request` response: {"msg":"Malformed purge request"}
```

This appears to be happening in other clients as well (https://github.com/fastly/fastly-js/issues/15) so it might be some sort of client generation issue.

**Comment by Integralist** [comment]
👋🏻 

I believe this was fixed in the [`v1.3.0`](https://github.com/fastly/fastly-php/blob/main/CHANGELOG.md#v130-2023-04-03) release.
